[package]
name = "rusttimetrack"
version = "1.8.3"
authors = ["Ricky Kresslein <ricky@unobserved.io>"]
edition = "2021"

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4", features = ["unstable-locales"] }
chrono_locale = "0.1"
csv = "1.2"
dbus = "0.9.7"
dbus-codegen = "0.10.0"
directories = "5.0"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk4-macros = "0.8.0"
itertools = "0.10.5"
log = "0.4"
num-derive = "0.3.3"
num-traits = "0.2.15"
once_cell = "1.17.1"
rusqlite = { version = "0.28.0", features = ["backup"] }
serde = { version = "1.0", features = ["derive"] }

[dependencies.gtk]
package = "gtk4"
version = "0.8.0"

[dependencies.adw]
package = "libadwaita"
version = "0.6.0"
features = ["v1_4"]